"""Generate the app's glyphs from GlimStone's glyph assortment.

Run from anywhere:  python scripts/gen_glyphs.py

scripts/glyphs.json is GlimStone's reference/glyphs.json, copied unchanged.
Each entry is one meaning: its drawing, where the drawing comes from, the
measured ink box and a square viewBox cropped to that ink, so glyphs from
different sets and grids fill their box alike. Refresh the copy from GlimStone
instead of editing it here, or the two apps that share the set drift apart.

Writes two files:
  web/src/components/glyphs.tsx      the action verbs buttons wear
  web/src/components/navGlyphs.tsx   navigation, domain and Settings tab symbols

Sidebar.tsx re-exports navGlyphs.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ASSORTMENT = {e["name"]: e for e in json.loads((ROOT / "scripts" / "glyphs.json").read_text(encoding="utf-8"))}

# The assortment covers every app that speaks GlimStone. A name in neither list
# is not generated: BombVault has no pause button and no captcha.
ACTION = [
    "IconRefresh",
    "IconUpload",
    "IconSearch",
    "IconUnlock",
    "IconPrune",
    "IconPlay",
    "IconStop",
    "IconBack",
    "IconForward",
    "IconLatest",
    "IconSelectAll",
    "IconClearSelection",
    "IconKey",
    "IconKeyRevoke",
    "IconLink",
    "IconInfo",
    "IconMail",
    "IconSignIn",
    "IconSignOut",
    "IconShieldOn",
    "IconShieldOff",
    "IconCompare",
    "IconCompressOff",
    "IconCompressAuto",
    "IconCompressMax",
    "IconSave",
    "IconEye",
    "IconEyeOff",
    # Brand marks. They are passed at the one call site that means them and
    # never wired into glyphFor, where a rule keyed on "coffee" or "repo" would
    # put a company's logo on settings that have nothing to do with it.
    "IconCoffee",
    "IconGithub",
]

NAV = [
    "IconDashboard",
    "IconContainers",
    "IconVM",
    "IconFiles",
    "IconZFS",
    "IconFleet",
    "IconReceiver",
    "IconRecovery",
    "IconFlash",
    "IconConfig",
    "IconAnomalies",
    "IconGear",
    "IconViewSimple",
    "IconViewAdvanced",
    "IconMore",
    "IconFolder",
    "IconLocal",
    "IconCloud",
    "IconDatabase",
    "IconDownload",
    "IconBackupNow",
    "IconRestore",
    "IconSync",
    "IconLive",
    "IconPower",
    "IconTrash",
    "IconPencil",
    "IconCopy",
    "IconCheck",
    "IconAdd",
    "IconClose",
    "IconTabGeneral",
    "IconTabRetention",
    "IconTabLook",
    "IconTabStorage",
    "IconSchedules",
    "IconTabOffsite",
    "IconNotifications",
    "IconTabIntegrity",
    "IconTabSecurity",
    "IconTabApps",
    "IconTabSystem",
]

# Glyphs that point along the reading direction, so a right-to-left layout
# mirrors them.
MIRRORED = {"IconBack", "IconForward", "IconSignIn", "IconSignOut"}

# Where a drawing comes from decides what the file owes its author. A source
# matching neither these nor NO_LICENCE stops the run, so a glyph from a new set
# cannot ship without its licence line.
LICENCES = [
    ("Streamline", "Free icons from Streamline - https://streamlinehq.com (CC BY 4.0)"),
    ("Font Awesome Free", "Font Awesome Free - https://fontawesome.com (icons: CC BY 4.0)"),
    ("Tabler Icons", "Tabler Icons - https://tabler.io/icons (MIT)"),
    ("Material Design Icons", "Material Design Icons - https://pictogrammers.com/library/mdi/ (Apache 2.0)"),
    ("Simple Icons", "Simple Icons - https://simpleicons.org (CC0)"),
]
# Drawings made for GlimStone or KnightLoader, and the reCAPTCHA mark, which is
# a trademark rather than licensed artwork.
NO_LICENCE = ("Drawn", "KnightLoader's drawing", "reCAPTCHA's mark")

TRADEMARKS = {
    "IconContainers": "Docker",
    "IconGithub": "GitHub",
    "IconCoffee": "Buy Me a Coffee",
    "IconCaptcha": "reCAPTCHA",
}

HEADER = """// %(headline)s
//
// GENERATED by scripts/gen_glyphs.py from scripts/glyphs.json, GlimStone's glyph
// assortment. Do not hand-edit: regenerate instead, or the next run silently
// overwrites the change.
//
// Attribution, required by the licences below:
%(licences)s
//
// Only Streamline's free 1000-icon subset is used
// (github.com/webalys-hq/streamline-vectors, core/solid), which is CC BY 4.0
// and may be redistributed. The 5771-icon set sold on streamlinehq.com is a
// separate product whose licence forbids redistribution.
%(trademarks)s//
// Every glyph takes the ink of its control through `currentColor`, so it is
// right in every theme, and is `aria-hidden`, because the control's label is
// its accessible name. Each viewBox is a square cropped to the drawing's
// measured ink, which makes glyphs from different sets the same size in the
// same 16px box.

import type { ReactNode } from "react";

function G({ box, mirror = false, children }: { box: string; mirror?: boolean; children: ReactNode }) {
  return (
    <svg
      width="16"
      height="16"
      viewBox={box}
      fill="currentColor"
      className={mirror ? "shrink-0 rtl:-scale-x-100" : "shrink-0"}
      aria-hidden="true"
    >
      {children}
    </svg>
  );
}
"""


def licence(name, source):
    for prefix, line in LICENCES:
        if source.startswith(prefix):
            return line
    if source.startswith(NO_LICENCE):
        return None
    raise SystemExit("%s comes from %r, which has no licence line in LICENCES" % (name, source))


def jsx(svg):
    """An entry's markup as JSX, without what the wrapper already sets.

    Streamline exports wrap their paths in a bare <g> and repeat the fill and a
    stroke width on every path; the wrapper's fill reaches them anyway, and a
    path left without a fill of its own also takes one a stylesheet sets on the
    <svg>.
    """
    s = svg.strip()
    bare = re.fullmatch(r"<g>\s*(.*?)\s*</g>", s, re.S)
    if bare:
        s = bare.group(1)
    s = re.sub(r'\s(?:fill="currentColor"|stroke-width="1")', "", s)
    s = re.sub(r"<(\w+)([^<>]*?)\s*>\s*</\1>", r"<\1\2 />", s)
    s = re.sub(r"\b([a-z]+)-([a-z]+)=", lambda m: m.group(1) + m.group(2).capitalize() + "=", s)
    return re.sub(r"/>\s*<", "/>\n<", s).split("\n")


def component(name):
    e = ASSORTMENT[name]
    mirror = " mirror" if name in MIRRORED else ""
    body = "\n".join("      " + line for line in jsx(e["svg"]))
    return '\n/** %s. */\nexport function %s() {\n  return (\n    <G box="%s"%s>\n%s\n    </G>\n  );\n}\n' % (
        e["means"],
        name,
        e["viewBox"],
        mirror,
        body,
    )


def write(path, headline, names):
    used = []
    for name in names:
        line = licence(name, ASSORTMENT[name]["source"])
        if line and line not in used:
            used.append(line)
    licences = "\n".join("//   " + line for line in sorted(used, key=[l for _, l in LICENCES].index))
    marks = [(n, TRADEMARKS[n]) for n in names if n in TRADEMARKS]
    trademarks = ""
    if marks:
        listed = ["%s (%s)" % m for m in marks]
        joined = listed[0] if len(listed) == 1 else ", ".join(listed[:-1]) + " and " + listed[-1]
        verb = "is a trademark" if len(listed) == 1 else "are trademarks"
        text = (
            "%s %s of %s, used unmodified and only to name what the control "
            "leads to, with no claim of endorsement or affiliation."
            % (joined, verb, "its owner" if len(listed) == 1 else "their owners")
        )
        trademarks = "//\n" + wrap(text) + "\n"
    out = [HEADER % {"headline": headline, "licences": licences, "trademarks": trademarks}]
    out.extend(component(n) for n in names)
    path.write_text("".join(out), encoding="utf-8", newline="")
    print("wrote %d glyphs to %s" % (len(names), path.relative_to(ROOT)))


def wrap(text, width=80):
    lines, line = [], "//"
    for word in text.split():
        if len(line) + 1 + len(word) > width:
            lines.append(line)
            line = "//"
        line += " " + word
    lines.append(line)
    return "\n".join(lines)


components = ROOT / "web" / "src" / "components"
write(components / "glyphs.tsx", "Action glyphs, the verbs buttons wear.", ACTION)
write(components / "navGlyphs.tsx", "Navigation, domain and Settings tab glyphs, re-exported by Sidebar.tsx.", NAV)
