name: Style

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  comments:
    uses: junkerderprovinz/junkerderprovinz/.github/workflows/comment-style.yml@89432b6436a2e1c6c480ad761f82e65490d14be8 # main
